from defQuestionAnswers import QuestionAnswers
from defQuestionAnswers import QuestionAnswerList

# 02.51 PM - You: Omg Lex, WHY?? -_-

input()
print("02.52 PM - Lex: Because I love you very much :)")
input()
print("02.52 PM - You: I'll give you $10 if you stop calling me that")
input()
print("02.52 PM - Lex: Only 10, that's pretty disappointing, I expect at least $25 to quit calling you that beautiful"
      " name")
input()
print("02.52 PM - Bella: Uhm, guys, maybe we should let Lotte explain exactly why we're here?")
input()
print("02.52 PM - Cas: Yes, I agree, I do not really care how much money you give each other")
input()
print("02.53 PM - Lex: What are you even talking about, I'M not the one who needs to give money")
input()
print("02.53 PM - Bella: Lex... that's not the point")
input()
print("02.53 PM - Lotte: Thanks Bella")
input()
print("02.53 PM - Lotte: Well, I don't have a specific purpose actually")
input()
print("02.53 PM - Lotte: You know, maybe we'll be smart enough to even solve this case")
input()
print("02.54 PM - Lotte: But that's not specifically why I added you, I don't know how you all feel about this, but I"
      " personally find it pretty creepy")
input()
print("02.54 PM - Lex: It's really creepy, all the people that think that Downhill is a peaceful town are insane")
input()
print("02.54 PM - Cas: I especially can't believe these murders started happening again after such a long time")
input()
print("02.54 PM - Cas: It has been 5 years right? And now these murders pop up again")
input()
print("02.55 PM - Bella: We are talking about the DK right? ,':/")
input()
print("02.55 PM - Cas: Yep")
input()
print("02.55 PM - Lex: Uuuhmm... what exactly are we talking about guys??")
input()
print("02.55 PM - You: I do kinda agree with Lex, I have no idea what we're talking about")
input()
print("02.56 PM - Lotte: It's about the Downhill Killer, aka DK. 5 years ago strange deaths started happening in the"
      " old, now supposedly haunted library")
input()
print("02.56 PM - Lex: What do you mean by weird deaths??")
input()
print("02.56 PM - Lotte: Bookcases were dropped on them and they died instantly")
input()
print("02.56 PM - You: They just dropped???")
input()
print("02.56 PM - Lex: OMG JUST LIKE THEY DID WITH THE KIDS THIS MORNING")
input()
print("02.57 PM - Bella: Yes Lex, that was why we were talking about it :)")
input()
print("02.57 PM - You: But why would there now be a killer also killing people by dropping bookcases on them?")
input()
print("02.57 PM - Cas: They actually never caught the DK, so it could be that they just found reason to kill again")
input()
print("02.58 PM - Bella: It's so scary to think about the fact that there's a serial killer just roaming around"
      " somewhere out there")
input()
print("02.58 PM - Lotte: Yes, it's horrible..")
input()
print("02.58 PM - You: It's a serial killer? So more then three deaths? How many were there??")
input()
print("02.58 PM - Lotte: 5 deaths in total, at least 5 years ago. Two children, two women and the old pastor")
input()
print("02.59 PM - Lex: Omg, even children, that's absolutely monstrous ")
input()
print("~ Select: a) 'Why were those women murdered??' ~")
print("~ Select: b) 'WHAT, why the hell would you murder a child?!?' ~")

Answer = QuestionAnswers("~ Type 'a' or 'b' please ~", QuestionAnswerList)
if Answer == 'a':
    input()
    print("02.59 PM - You: Why were those women murdered??")
    import Choice4a

else:  # b
    input()
    print("02.59 PM - You: WHAT, why the hell would you murder a child?!?")
    import Choice4b