# print("02.31 PM - You: What?? Dead?! How old were they?? D:")

input()
print("02.31 PM - Lotte: I'm pretty sure they were like 14")
input()
print("02.31 PM - You: That's so scary")
input()
print("02.31 PM - You: How did that even happen?")
input()
print("02.31 PM - Lotte: Well, if you push hard enough I'm sure you'll get the bookcases to collaps")
input()
print("02.32 PM - You: Yeah you're right, that library is pretty old... the bookcases are probably rotten, I dont think"
      " they're very sturdy anymore..")
input()
print("02.32 PM - Lotte: But do you think they are SO unsturdy that they would just fall over and crush two 14 year "
      " olds..?")
input()
print("02.32 PM - You: Maybe they climbed the bookcases to get something from the top shelf..?")
input()
print("02.32 PM - You: I used to do that all the time")
input()
print("02.33 PM - Lotte: Oh, did you go there often?")
input()
print("02.33 PM - You: I used to")
input()
print("02.33 PM - You: I haven't really been there since it closed")
input()
print("02.33 PM - Lotte: There are a lot of rumors that it's haunted")
input()
print("02.34 PM - You: What are you suggesting?")
input()
print("02.34 PM - You: That A GHOST threw the bookcase on top of them...")
input()
print("02.34 PM - Lotte: Well, a bookcase doesn't fall out of nowhere, there must be SOME reason")
input()
print("02.34 PM - You: I don't believe in paranormal stuff like that")
input()
print("02.35 PM - Lotte: But are they really THAT unsturdy")
input()
print("02.35 PM - Lotte: Surely they wouldn't just randomly tip over")
input()
print("02.35 PM - You: So you think something or maybe someone pushed it??")
input()
print("02.35 PM - Lotte: Yeah, I guess so, I mean, don't you agree that it's all very strange")
input()
print("02.36 PM - You: Well, I haven't really looked into it, but yeah, I suppose so")
input()

import CommonFileAfterChoice1
